server:
  port: 8002
  servlet:
    context-path: /api

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_user_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true