server:
  servlet:
    context-path: /api

spring:
  datasource:
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret-key: supersecretkey1234567890supersecret
  duration: 86400000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

