server:
  port: 8009
  servlet:
    context-path: /api

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_payment_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

stripe:
  secret:
    key: sk_live_
  public:
    key: pk_live_
  callback:
    url: http://localhost:5173

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true