server:
  port: 8006
  servlet:
    context-path: /api

spring:
  application:
    name: pricing-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_pricing_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

stripe:
  secret:
    key: sk_live_
  public:
    key: pk_live_
  callback:
    url: http://localhost:5173